name: Artemis
url: https://github.com/Dreyer/hexo-theme-artemis

menu:
  主页: /
  目录: /archives
  标签: /tags
  关于: /about

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:

# Analytics
mathjax: false
google_analytics:

# Copyright Infomation
copyright:
  since:
  name:
  url:
